### ISSUE TITLE
compiling of louvain_cython

### ISSUE THREAD

**Issue by pbezz1** [shazzzm/partial_correlation_financial_networks#1]
Hi
I'm getting this error when compiling louvain_cython. I'm using Visual Studio Code on Windows.

The command I'm giving is "python setup.py build_ext --inplace" as specified in compile_cython.sh.

louvain_cython.c(613): fatal error C1083: Cannot open include file: 'numpy/arrayobject.h': No such file or directory

Thanks
Patrick

**Comment by pbezz1** [comment]
Hi 
I solved my issue by adding "--include-dirs="/Anaconda3/envs/MyEnv/Lib/site-packages/numpy/core/include/"" to the compile script.

**Comment by shazzzm** [comment]
Thanks for sharing your solution!
