### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by pbezz1** [shazzzm/partial_correlation_financial_networks#2]
Hi
I'm getting this error when compiling louvain_cython. I'm using Visual Studio Code on Windows.

The command I'm giving is "python setup.py build_ext --inplace" as specified in compile_cython.sh.

louvain_cython.c(613): fatal error C1083: Cannot open include file: 'numpy/arrayobject.h': No such file or directory

Thanks
Patrick

**Comment by shazzzm** [comment]
Hi

I don't have a Windows machine to test this on, so I'm not familiar with how to use cython on windows. However that sounds like you could be missing the numpy development libraries? Either that or are you sure they're in your compiler path?

**Comment by pbezz1** [comment]
Hi Tristan
I did manage to compile by adding "--include-dirs="/Anaconda3/envs/MyEnv/Lib/site-packages/numpy/core/include/"" in the compile script.

Regards
Patrick
