### ISSUE TITLE
Can you share the code for figure 10 please?

### ISSUE THREAD

**Issue by pbezz1** [shazzzm/partial_correlation_financial_networks#3]
Hi
I'm getting this error when compiling louvain_cython. I'm using Visual Studio Code on Windows.

The command I'm giving is "python setup.py build_ext --inplace" as specified in compile_cython.sh.

louvain_cython.c(613): fatal error C1083: Cannot open include file: 'numpy/arrayobject.h': No such file or directory

Thanks
Patrick

**Comment by pbezz1** [comment]
Hi
Could you kindly share the code of figure 10 please?

Thanks
Patrick

**Comment by shazzzm** [comment]
You should be able to get Figure 10 out by running "diff_portfolio_centrality.py". Let me know if that doesn't work.

**Comment by pbezz1** [comment]
Hi Tristan

Yes I managed. Thanks

**Comment by shazzzm** [comment]
Great! If you're doing anything particularly interesting with the work (and can tell me about it) I'd love to hear. My email is on my profile!
